version: "3.8"

services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-server
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT_CONFIG_PATH=/qdrant/config/production.yaml
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/collections"]
      interval: 30s
      timeout: 10s
      retries: 3

  # FastAPI RAG Server
  rag-api:
    build: .
    container_name: qdrant-rag-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock # For Docker-in-Docker if needed
    environment:
      - QDRANT_URL=http://qdrant:6333
      - EMBEDDINGS_PROVIDER=fastembed
      - MODEL_NAME=BAAI/bge-small-en-v1.5
      - API_HOST=0.0.0.0
      - API_PORT=8000
    depends_on:
      qdrant:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  qdrant_data:
    driver: local
